config/routes.rb
Rails.application.routes.draw do

  #root 'pages#show'
  root 'boards#index'

  get 'login'		=> 'sessions#new'
  post 'login'		=> 'sessions#create'
  delete 'logout'	=> 'sessions#destroy'
  patch 'like' => 'boards#like'
  patch 'unlike' => 'boards#unlike'
  resources :boards do
  	resources :replies
      get :autocomplete_board_b_category, :on => :collection
  end
  resources :users
  
end

app/models/board.rb
require 'obscenity/active_model'
require 'obscenity/rack'

class Board < ActiveRecord::Base
	has_many :replies
	accepts_nested_attributes_for :replies
	validates :b_category, presence: true
	validates :b_content, obscenity: { sanitize: true, replacement: :stars }
	after_initialize :init

	def init
		self.b_click_count ||= 0
		self.b_like ||= 0
	end

	def self.search(search)
		if search
			where('b_category LIKE ?', "%#{search}%")
		else
			scoped
		end
	end
end

app/models/reply.rb
class Reply < ActiveRecord::Base
	belongs_to :board
	validates :board_id, presence: true
	validates :r_content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base    
  validates :u_id, presence: true
  validates :u_pwd, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
	autocomplete :board, :b_category
	def new
		@board = Board.new
	end

	def create
		@board = Board.new(board_params)
		
		if params[:board][:b_category] == "#"
			flash[:danger] = "태그 제대로 써라"
			redirect_to :back
		elsif params[:board][:b_category] != '#' && params[:board][:b_content] == ""
			flash[:danger] = "내용 제대로 써라"
			redirect_to :back
		else
			@board.save
			redirect_to root_path
		end

	end

    def index
        if(params[:b_category])
            @boards = Board.paginate(page: params[:page], :per_page => 10).where("b_category = ? ", params[:b_category])
        elsif(params[:b_click_count])
            @boards = Board.paginate(page: params[:page], :per_page => 10).order("b_click_count DESC")
        elsif(params[:b_like])
            @boards = Board.paginate(page: params[:page], :per_page => 10).order("b_like DESC")
        elsif params[:search]
            @boards = Board.paginate(page: params[:page], :per_page => 10).search(params[:search])
        else
            @boards = Board.paginate(page: params[:page], :per_page =>10).order("created_at DESC")
        end
    end

	def show
		@board = Board.find(params[:id])
		@board.increment! :b_click_count

	end

	def upClick
		@board = Board.find(params[:id])
		@board.increment! :b_click_count
	end

	def edit
		
	end

	def like
		@board = Board.find(params[:id])
		@board.increment! :b_like
	end

	def unlike
		@board = Board.find(params[:id])
		@board.decrement! :b_like
	end

	def update
		
	end

	def destroy
		Board.find(params[:id]).destroy
		redirect_to :back
	end

	private
	def board_params
		params.require(:board).permit(:b_category, :b_content, :b_click_count, :b_like, :b_picture)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@boards = Board.all
  	@click_count_list = Board.order("b_click_count DESC")
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

	def create
		@board = Board.find(params[:board_id])
		@reply = @board.replies.create(reply_params)
		if @reply.save
    		redirect_to board_path(@board)
    	else
    		redirect_to root_url
    	end
	end

	def index
		
	end

	def destroy
		Board.find(params[:board_id]).replies.find(params[:id]).destroy
		redirect_to :back
		flash[:success] = "댓글삭제완료"
	end

	private

	def reply_params
		params.require(:reply).permit(:r_content)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(u_id: params[:session][:id].downcase)
    if user
      log_in(user)
  	  redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
   	end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]
  before_action :correct_user, 	 only: [:show]

  def show
  	@user = User.find(params[:id])
  	@boards = Board.paginate(page: params[:page], :per_page => 5).all.order("created_at DESC")
  end

  private
    def logged_in_user
      unless logged_in?
        flash[:danger] = "로그인 하세요"
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
	def timestamp_division(board)
		difference = Time.zone.now - board.created_at
		# 0 ~ 59초전
		if difference < 60
			"방금전"
		# 1분 ~ 60분전
		elsif difference > 60 && difference < 3600
			(difference/60).to_i.to_s + "분전"
		# 1시간 ~ 24시간
		elsif difference > 3600 && difference < 86400
			(difference/3600).to_i.to_s + "시간전"
		# 하루 전 ~ 과거
		else
			board.created_at.strftime("%m/%d %H:%M")
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper

end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
	session[:user_id] = user.id 
  end

  def current_user?(user)
    user == current_user
  end

 # Returns the user corresponding to the remember token cookie.
  def current_user
	if (user_id = session[:user_id])
  		@current_user ||= User.find_by(id: user_id)
	elsif (user_id = cookies.signed[:user_id])
  		user = User.find_by(id: user_id)
    	log_in user
    	@current_user = user
    end
  end

  def logged_in?
	!current_user.nil?
  end

  def log_out
    session.delete(:user_id) 
	  @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/edit.html.erb
<p>edit</p>

app/views/boards/index.html.erb
<% provide(:title, "세레기통") %>
<body>
	<div class="stats">
	    <%= link_to "All", boards_path, class:"btn btn-success" %>
	    <%= link_to "조회순", boards_path(:b_click_count => 1),class:"btn btn-success" %>
		<%= link_to "추천순", boards_path(:b_like => 1),class:"btn btn-success" %>
	</div>

	<div class="search-class">
		<%= form_tag(boards_path, :method => "get", id: "search-form") do %>

		  <%=link_to '#', '#' %>
		  
		<%= text_field_tag :search, params[:search], 
		  	class: "search-query", 
		  	placeholder: " 해시태그를 입력하세요.",
		   	type: "search", 
		   	data: { autocomplete: autocomplete_board_b_category_boards_path },
		   	remote: true 
		%> 

		  <%= submit_tag "검색", :b_category => nil ,class:"btn btn-default btn-sm", data: {disable_with: "검색중.."}%>
		<% end %>
	</div>
	
	<table class="table">
		<tr class ="activerow">
			<td class = "board-category">태그</td>
			<td class = "board-content">내용</td>
			<td class = "board-click-count">조회수</td>
			<td class = "board-like">추천</td>
			<td class = "board-time">작성 일자</td>
		</tr>

		<% @boards.each_with_index do |board, index| %>
			<tr class="lovelyrow" >
				<td class = "board-category">
					<%= link_to truncate(board.b_category,length:10), 
						boards_path(:b_category => board.b_category) %>
				</td>
   				
   				<td class = "board-content" >
   				<a href='/boards/<%= board.id %>'>
				<div>
			    	<%= truncate(board.b_content, length:20) %>
	                <label style="color: #ff3333">
	                	(<%= board.replies.size %>)
	                </label>
	            </div>
	            </a>
				</td>

				<td class = "board-click-count-row">
					<%= board.b_click_count %>
				</td>
				<td class = "board-like-row">
					<%= board.b_like %>
				</td>
				<td class = "board-time-row">
					<%= timestamp_division(board) %><p>
				</td>
		<% end %>

	</table>
	<div class="paginate">
		<%= will_paginate %>
	</div>

</body>
<script>

	$(document).ready(function(){
		
		$('.search-query').bind('railsAutocomplete.select', function(event, data){
  		$('.search-form').trigger('click')
		});

		$(".search-test").autocomplete({source: 'boards/us_states'});
	});

</script>

app/views/boards/like.js.erb
$("#like").html("<%= @board.b_like %>");
$("#like_button").html('<p><div class = "thumbs"><%= link_to "추천취소",  unlike_path(:id => @board.id), 
                method: :patch, 
                remote: true, class:"glyphicon glyphicon-thumbs-down"%> <p><br><p></div>');

app/views/boards/new.html.erb
<% provide(:title, "글쓰기") %>
<div class="text-center">
	<%= form_for(@board) do |f| %>
		<div id="board_area">
			<%= f.text_area :b_category, class: "b_category_area",
			size: "40x2", placeholder: "해시태그를 입력해주세요.
( ex: 학과  연애  뒷담 )" %>
			<button type="button" class="btn btn-xs btn-success" 
			data-toggle="tooltip" rel="tooltip"	data-placement="right" 
			title="태그명을 입력하고 띄어쓰기를 하면,
			<br /> 자동으로 # 이 추가됩니다.
			<br /> ex) 연애 + spacebar">
			?</button>
		</div>
		<%= f.text_area :b_content, class: "b_content_area",
		size: "40x15", placeholder: "자유롭게 적어주시되, 심한 비방 혹은 욕설을
사용할 경우에는 삭제됩니다." %>
		<%= f.submit "등록", class: "btn btn-success",
		data: { confirm: '정말 제보하시겠어요?', disable_with: "등록중.." } %>
		<% end %>
</div>

<script>


	$('document').ready(function() {

		var count = 0;
		var total = "";
		var word = "";
		var arr = new Array();
		$("#board_b_category").keyup(function(key) {

                if (key.keyCode == 32) {
                    word = $("#board_b_category").val();
                    arr[count] = word;
				    total = "<a href='#'>#" + word +"</a>";
					$("#board_area").html(total);
					$("#board_b_category").val(arr);
					count++;
                }
		})
		
		$('#new_board').submit(function(){ 

    		$('<input>').attr('type', 'hidden')
            .attr('name', "board[b_category]")
            .attr('value', "#"+word)
            .appendTo('#new_board');

    	});
	});

    $(function () {
        $("[rel='tooltip']").tooltip({placement: 'right',trigger: 'manual', html: true}).tooltip('show');
    });
</script>

app/views/boards/show.html.erb
<% provide(:title, @board.b_content) %>

<html>
<head>
  <title></title>
</head>
<body>
  <div class="text-center">
          조회수 : <%= @board.b_click_count %> |  
          추천수 : <span id="like"><%= @board.b_like %></span>
          <span id="like_button"><p>
            <div class = "thumbs">
              <%= link_to "추천", 
                like_path(:id => @board.id), 
                method: :patch, 
                remote: true, 
                class:"glyphicon glyphicon-thumbs-up"%><p><br><p>
            </div>
          </span>
    <div class = "board-show">
      <td>
        <%=link_to @board.b_category, boards_path(:b_category => @board.b_category) %>
      </td>
    </div>

    <hr>
    <div class = "board-content-show">
      <%= @board.b_content %>
    </div>
    <hr>

    <div class = "comment-info-show">
      댓글 보기
      <p>
    </div>
    <div class = "comment-show">
      <table class="table table-bordered">
      <tr>
          <td class = "comment-writer">작성자</td>
          <td class = "comment-content">내용</td>
          <td class = "comment-time">작성시간</td>
      </tr>
      
      <% @board.replies.each do |r| %>  
        <tr>
          <td class = "comment-writer">익명</td>
          <td class = "comment-content"><%= r.r_content %></td>
          <td class = "comment-time"><%= timestamp_division(r) %></td>
        </tr>
      <% end %>
      </table>
    </div>
    
    <%= form_for([@board, @board.replies.build]) do |f| %>
      <div class="comment_write">
        <hr>
        <%= f.text_field :r_content, placeholder: "  댓글을 입력하세요." , id: "comment-field"%>
        <%= f.submit "등록", class:"btn btn-success btn-sm", data:{disable_with: "등록중.."}%>
      </div>
    <% end %>
  </div>

</body>
</html>

	

app/views/boards/unlike.js.erb
$("#like").html("<%= @board.b_like %>");
$("#like_button").html('<p><div class = "thumbs"><%= link_to "추천",  like_path(:id => @board.id), 
                method: :patch, 
                remote: true, class:"glyphicon glyphicon-thumbs-up"%> <p><br><p></div>');

app/views/layouts/_footer.html.erb
<footer>
<p><br><p>세레기통 2015<p><br><p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to "세레기통", root_path , class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <!-- <li><%= link_to "홈", root_path %></li> -->
          <li><%= link_to "글쓰기", new_board_path , :id => "write"%></li>
        <!--<li><%= link_to "게시판", boards_path %></li>-->
      </ul>
      
    </div><!--/.nav-collapse -->
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <div class="container-message">
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

    <div class="container-debug">
      <%= yield %>
      <!--<%= debug(params) if Rails.env.development? %>-->
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<% provide(:title, "세종대 대나무숲") %>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <style type="text/css">
    h2{
        margin: 0;     
        color: #fff;
        padding-top: 130px;
        font-size: 52px;
        font-family: "trebuchet ms", sans-serif;    
    }
    </style>
  </head>
  <body>
    <div class="bs-example">
        <div id="myCarousel" class="carousel slide" data-interval="3000" data-ride="carousel">
          <!-- Carousel indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>   
           <!-- Wrapper for carousel items -->
            <div class="carousel-inner">
                <div class="active item">
                    <h2><%=link_to @click_count_list.first.b_category, 
                        boards_path(:b_category => @click_count_list.first.b_category) %>
                    </h2>

                    <hr>
                    <div class="carousel-caption">
                    <h3><%=link_to @click_count_list.first.b_content, 
                                @click_count_list.first %>
                    </h3>
                      
                    </div>
                </div>
                <div class="item">
                    <h2><%=link_to @click_count_list.second.b_category,
                         boards_path(:b_category => @click_count_list.second.b_category) %>
                     </h2>
                    <hr>
                    <div class="carousel-caption">
                    <h3><%=link_to @click_count_list.second.b_content,
                                   @click_count_list.second %>
                    </h3>
                      
                    </div>
                </div>
                <div class="item">
                    <h2><%=link_to @click_count_list.third.b_category,
                         boards_path(:b_category => @click_count_list.third.b_category) %>
                     </h2>
                    <hr>
                    <div class="carousel-caption">
                    <h3><%=link_to @click_count_list.third.b_content,
                                   @click_count_list.third %>
                    </h3>
                    </div>
                </div>
            </div>
            <!-- Carousel controls -->
            <a class="carousel-control left" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="carousel-control right" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>

    <div class="home-middle-container">
      <!-- Example row of columns -->
      <div class="row">
        <% @boards.each do |board| %>
          <div class="col-md-4">
            <h3><%= board.b_category %></h3><br>
            <p><%= board.b_content %> </p><br>
            <p>
            <div class="more_button">
            <%= link_to "더보기", board, class:"btn btn-primary"%>
            </div>
          </div>
        <% end %>
      </div> <!-- /container -->
    </div>
  </body>
  <hr>
</html>                                   

app/views/replies/_reply_form.html.erb
<%= form_for(Reply.new) do |f| %>
  <div class="field">
  	<!-- <input type="hidden" name="reply[board_id]" value="1"> -->
    <%= f.text_area :r_content, placeholder: "댓글 작성" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, "Admin Page") %>
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<div class="admin">	
		<h1> Admin Page </h1><p><br>
		
		<% @boards.each do|b| %>
			글 번호 : <%= b.id %><p>
			글 태그 : <%= b.b_category %><p>
			글 내용 : <%= b.b_content %><p>
			<%= link_to "삭제", board_path(b.id), 
			method: :delete, 
			class:"btn btn-danger", 
			id: "btn-admin-destroy",
			data: {confirm: "삭제합니까?", disable_with: "삭제중.."} %><p><br>

			<% b.replies.each do |r| %>
				댓글 번호 : <%= r.id %><p>
				댓글내용 : <%= r.r_content %>
				<%= link_to "댓글삭제", board_reply_path(:board_id => b.id , :id => r.id),
				method: :delete,
				class:"btn btn-danger",
				id: "btn-admin-destroy",
				data:{confirm:"삭제?", disable_with: "삭제중.."} %><p><br>
			<% end %><p>

		<% end %>

		<div class="paginate">
			<%= will_paginate @boards %>
		</div>
		
	</div>
</body>
</html>